### ISSUE TITLE
Mobility::InvalidLocale

### ISSUE THREAD

**Issue by durcak** [shioyama/friendly_id-mobility#14]
Hi,

I am trying to use friendly_id-mobility with moblity and jsonb storage for translated columns. Everything works fine for me with mobility gem, but when I add friendly_id-mobility its working but in tests I am getting error:

```
Mobility::InvalidLocale:
        :tr is not a valid locale
```

In my application.rb I have this config for locales:

 ```
config.i18n.default_locale = :en
    config.i18n.fallbacks = true
    config.i18n.available_locales = [:en, :sk, :hu]
```

Where id :tr locale coming from? Can you please help?

Thanks

**Comment by shioyama** [comment]
This is not a Mobility problem, but FWIW I think probably `true` is being interpreted as a locale, hence you get `tr`.

Maybe this will help:

https://stackoverflow.com/questions/4223806/how-to-use-rails-i18n-fallback-features

**Comment by durcak** [comment]
@shioyama I used setup `config.i18n.fallbacks = [:en, :sk, :hu]` in application.rb and in test.rb too, but without change :(

**Comment by kevynlebouille** [comment]
@shioyama @durcak are-you using column_suffix option for your translated column ?
I ran into the same issue because I used `column_suffix = '_translations'` (ex: name_translations)
Into the `set_slug` method (FriendlyId::Mobility), there is a regexp catching the column_suffix

I monkey patch this with adding an `\Z` at the end of that regexp.
